version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=public.ecr.aws/v9y0z8s7/lektionsdemo
      - echo "loggin in to AWS ECR"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$(date +'%Y%m%d-%H%M') .
      - docker push $REPOSITORY_URI --all-tags
      - printf '[{"name":"lektionsdemo", "imageUri":"%s"]]' $REPOSITORY_URI:latest >imagedefinitions.json

artifacts:
  files: imagedefinitions.json